describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/login')
    cy.get('[data-cy="email"]').type('admin@biblio.com')
    cy.wait(1000)
    cy.get('[data-cy="password"]').type('admin1234')
    cy.wait(1000)
    cy.get('[data-cy="login-button"]').click()
    cy.wait(1000)
    cy.get('[data-cy="book-link"]').click()
    cy.wait(1000)
    cy.get('[data-cy="isbn"]').type('978-3-16-148410-0')
    cy.wait(1000)
    cy.get('[data-cy="name"]').type('Livro Exemplo')
    cy.wait(1000)
    cy.get('[data-cy="author"]').type('Autor Exemplo')
    cy.wait(1000)
    cy.get('[data-cy="publisher"]').type('Editora Exemplo')
    cy.wait(1000)
    cy.get('[data-cy="genre"]').type('Gênero Exemplo')
    cy.wait(1000)
    cy.get('[data-cy="image"]').type('https://example.com/image.jpg')
    cy.wait(1000)
    cy.get('[data-cy="year"]').clear().type('2022')
    cy.wait(1000)
    cy.get('[data-cy="create-book-form"]').submit()
    cy.wait(1000)
  })
})